[env:esp32-s3-devkitc-1]
platform = espressif32
board = dfrobot_firebeetle2_esp32s3
framework = arduino

monitor_speed = 115200

; Enable native USB
board_build.usb_mode = 1
board_build.usb_cdc_on_boot = 1

build_src_filter = +<*> -<readmouse_input.cpp>
